# Generated by Django 4.2.7 on 2024-04-07 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("poster_path", models.URLField(blank=True, max_length=255, null=True)),
                ("overview", models.TextField()),
                ("release_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
