# Generated by Django 4.2.7 on 2024-04-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="created_on",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="updated_on",
            new_name="date_updated",
        ),
    ]
