# Generated by Django 4.2.7 on 2024-04-12 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0002_movie_rating_movie_tag_alter_movie_poster_path"),
        ("watchlists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="overview",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="poster_path",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="title",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
